### ISSUE TITLE
Update Readme.md to mention BepInEx is a dependencie

### ISSUE THREAD

**Issue by XolbyNax** [BrandenEK/Blasphemous.Modding.Installer#62]
I just downloaded the latest and greatest, but the mod installer can't start the game because it's missing this file:
![image](https://github.com/user-attachments/assets/0c3c7855-c06f-40f8-8aee-14d7a20cd429)

Also, if I click to download the modding tools, the program crashes, and I get this:
![image](https://github.com/user-attachments/assets/c25bbaba-a11e-45a1-b18f-ea1118ee33bb)

After searching what is doorstop_config.ini, I found out it was a file rom BepInEx, and then I found out I first need to launch the game for BepInEx to generate all its files and folders.

Why is this not mentioned in the ReadMe? It only says to follow the BeInEx instructions for Unix, but nowhere it's said that's also be needed for Windows.

I thought Mod Installer was bugged.

Please, write in all capitals, bold, and italics:

**_[BEPINEX](https://github.com/BepInEx/BepInEx/releases) IS NECESARY FOR MOD INSTALLER TO WORK_**

**Comment by BrandenEK** [comment]
Bepinex isn't a dependency, it's part of the modding tools which it doesn't let you download because it crashes. Thank you for reporting this, I need three pieces of information from you
- Send the file at {AppData}/Roaming/BlasModInstaller/Settings.cfg
- Where you do you have the BlasModInstaller.exe program?
- After starting 1.7.x, did you ever see "Click here to locate Blasphemous.exe" or were mods already showing up the first time you opened it?

**Comment by XolbyNax** [comment]
> Bepinex isn't a dependency, it's part of the modding tools which it doesn't let you download because it crashes. Thank you for reporting this, I need three pieces of information from you
> 
> * Send the file at {AppData}/Roaming/BlasModInstaller/Settings.cfg
> * Where you do you have the BlasModInstaller.exe program?
> * After starting 1.7.x, did you ever see "Click here to locate Blasphemous.exe" or were mods already showing up the first time you opened it?

```
{
  "lastSection": 0,
  "games": [
    {
      "id": "blas1",
      "rootFolder": "",
      "launch": {
        "runModded": true,
        "runConsole": true
      }
    },
    {
      "id": "blas2",
      "rootFolder": "",
      "launch": {
        "runModded": true,
        "runConsole": true
      }
    }
  ],
  "pages": [
    {
      "id": "blas1mods",
      "sort": 0,
      "filter": 0,
      "time": "2024-10-31T21:23:10.0561897+02:00"
    },
    {
      "id": "blas1skins",
      "sort": 0,
      "filter": 0,
      "time": "2024-10-31T21:24:08.75704+02:00"
    },
    {
      "id": "blas2mods",
      "sort": 0,
      "filter": 0,
      "time": "2024-10-30T14:26:18.211919+02:00"
    }
  ],
  "window": {
    "location": "0, 0",
    "size": "1280, 720",
    "isMaximized": false
  }
}
```

BlasModInstaller.ex is in the same folder as Blasphemous.exe. In the root folder of the game.

As for the last question, I wasn't asked anything. It took 2 or 3 seconds, and the mods showed up. 
![image](https://github.com/user-attachments/assets/8e653cae-144d-49de-a815-86cd78e75bd6)

**Comment by XolbyNax** [comment]
Anyways, I'm going to try the manual install, since the automatic method failed me. Wish me luck.

**Comment by BrandenEK** [comment]
Thank you for that info, that let me figure out what the problem was (If the installer is in the same folder as the game, it messes up).

As a temporary fix, either move the mod installer to a different folder or edit the Settings.cfg file to change the blas1RootFolder property.

You don't have to install BepInEx at all, it is included in the modding tools, along with additional files specific to Blasphemous.

I shall fix this issue as soon as possible, thank you again for posting an issue here and assisting me with debugging.

**Comment by BrandenEK** [comment]
v1.7.2 fixes this issue
